policy_dt: 0.02
physics_dt: 0.005
decimation: 4
action_scale: 0.25
action_clip: 1.0
action_delta_limit: 0.15
low_state_timeout_s: 0.1
policy_timeout_s: 0.01
sim_domain_id: 1
real_domain_id: 0
sim_interface: lo

