enabled: true
friction:
  static: [0.3, 1.0]
  dynamic: [0.3, 1.0]
  restitution: [0.0, 0.0]
base_mass_add: [-1.0, 3.0]
joint_reset_velocity: [-1.0, 1.0]
push:
  enabled: true
  interval_s: [5.0, 5.0]
  velocity_xy: [-0.5, 0.5]
observation_noise: true

