enabled: false
friction:
  static: [1.0, 1.0]
  dynamic: [1.0, 1.0]
  restitution: [0.0, 0.0]
base_mass_add: [0.0, 0.0]
joint_reset_velocity: [0.0, 0.0]
push:
  enabled: false
  interval_s: [5.0, 5.0]
  velocity_xy: [0.0, 0.0]
observation_noise: false

