# Actor/Critic neural-network architecture used by flat, rough, and sim2real PPO.
init_noise_std: 1.0
actor_obs_normalization: false
critic_obs_normalization: false
actor_hidden_dims: [512, 256, 128]
critic_hidden_dims: [512, 256, 128]
activation: elu
