runner: OnPolicyRunner
num_steps_per_env: 24
max_iterations: 1500
save_interval: 100
empirical_normalization: false
clip_actions: 1.0
policy: ../policy/mlp_base.yaml
algorithm: ../algorithm/ppo_base.yaml
