runner: OnPolicyRunner
num_steps_per_env: 8
max_iterations: 2
save_interval: 1
empirical_normalization: false
clip_actions: 1.0
policy: ../policy/mlp_smoke.yaml
algorithm: ../algorithm/ppo_smoke.yaml
